### ISSUE TITLE
About the 1st milestone: implementing default conky functionality

### ISSUE THREAD

**Issue by npyl** [npyl/conky-for-macOS#12]
The 1st milestone is all about implementing the required functionality for showing the default conky config!

This requires implementing following:

- [ ] update_running_processes() #8 

- [ ] update_running_threads() #7 

- [ ] get_top_info() #10 

- [ ] update_meminfo() #6 

- [ ] get_freq()

- [ ] get_net_stats()

**Comment by npyl** [comment]
NOTE: `update_meminfo()` has been implemented but because I am using some apple code I can't tick it yet, unless I modify the code to comply with the restrictions of the license
